# Generated by Django 6.0.5 on 2026-05-20 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_update_etape_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchebc',
            name='comite_conformite',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='date_attribution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='marque',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='delai_reception_jours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='statut',
            field=models.CharField(choices=[('en_attente_livraison', 'en attente de livraison'), ('receptionne_et_stocke', 'Réception et stockée'), ('refuse', 'refus (motif)')], db_index=True, default='en_attente_livraison', max_length=30),
        ),
    ]
