# Generated by Django 6.0.5 on 2026-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_journalaudit_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('demande_soumise', 'Demande soumise'), ('demande_validee', 'Demande validée'), ('demande_rejetee', 'Demande rejetée'), ('decharge_generee', 'Décharge générée'), ('decharge_signee', 'Décharge signée'), ('retour_enregistre', 'Retour enregistré'), ('alerte_stock', 'Alerte stock'), ('alerte_delai', 'Alerte délai livraison'), ('import_staging', 'Import en attente de révision')], db_index=True, default='alerte_stock', max_length=30),
        ),
    ]
