# Generated by Django 6.0.5 on 2026-05-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_softdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBeneficiaire',
            fields=[
                ('id_type_beneficiaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'type de bénéficiaire',
                'verbose_name_plural': 'types de bénéficiaire',
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id_type_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'type de service',
                'verbose_name_plural': 'types de service',
            },
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_service',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='id_type_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='users.typebeneficiaire'),
        ),
        migrations.AddField(
            model_name='service',
            name='id_type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.typeservice'),
        ),
    ]
